### Marginal Slopes with Interactions

When there is an interaction between a categorical variable and a continuous variable, it is natural to want to estimate the slope at each level of
the categorical variable, the marginal slope. This is very similar to the marginal mean, but instead of the average predicted outcome per group, it's
the average predicted slope per group.

As we mentioned when discussing [marginal means with interactions](#interactions-between-categorical-variables), regression coefficients tell only a
partial story when there is an interaction involved. Regression coefficients will estimate the slope in the reference group and the difference between
the slope in the reference group and other groups, but not explicitly estimate the slope in each group. Marginal slopes does this.

#### Example

Here we interact "sex" (binary) with "age" (continuous). The regression coefficients tell us that the slope among males (the reference group) is
-0.49, and the difference in slopes between groups is -0.022. The marginal mean gives us the slope amongst males again, as well as -0.49 + (-0.02) =
0.51 as the slope among females.
